os: osx
language: generic
python: 3.6
osx_image: xcode12
env:
   global:
     - CONAN_REFERENCE: "darwin-toolchain/1.0.8"
     - CONAN_USERNAME: "theodelrieu"
     - CONAN_LOGIN_USERNAME: "theodelrieu"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://conan.bintray.com"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
